import type { Metadata } from "next";
import "./globals.scss";
import { ThemeProvider } from "@/providers/theme"

import { Toaster } from '@/components/ui/sonner';

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { cn } from "@/lib/utils";
import NavigationFrame from "@/components/navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
            "min-h-screen bg-background font-sans antialiased m-0 box-border"
        )}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
          <NavigationFrame />
            <div className="pt-[5.5rem]" suppressHydrationWarning suppressContentEditableWarning>
                {children}
            </div>
            <Toaster />
          </ThemeProvider>
        </body>
    </html>
  );
}
